Repository smaranjitghose/img_ai_app_boilerplate, pull requests merged in 2020-10, with the labels that each got.

#13 Fixing NumPy bug
  requirements.txt
Labels: Hacktoberfest

#15 Added Multiple Pages
  Feedback.MD
  Guides/GKE_Guide.md
  Guides/Heroku_Guide.MD
  Guides/Microsoft_Azure_Guide.MD
  README.md
  app.py
  firebase_bro.py
Labels: PR: reviewed-approved, hacktoberfest-accepted

#16 Tried to Clean and Organise the Readme file
  Feedback.MD
  Guides/Firebase_Setup.MD
  Guides/Heroku_Guide.MD
  README.md
  firebase_bro.py
Labels: PR: reviewed-approved, hacktoberfest-accepted

#18 Created AWS Guide
  Guides/AWS_EC2_Guide.md
Labels: documentation, hacktoberfest-accepted, slop2020
