Repository smaranjitghose/img_ai_app_boilerplate, pull requests merged in 2021-01, with the labels that each got.

#36 updated the contributing file
  CONTRIBUTING.md
  assets/Readme_Assets/clone.png
  assets/Readme_Assets/compareandpull.png
  assets/Readme_Assets/createpull.png
Labels: Easy, SWoC2021

#35 added contributing.md file
  CONTRIBUTING.md
  assets/images/clone.png
Labels: DWOC, Easy, Level-1, PR: reviewed-changes-requested, PR: unreviewed, SWoC2021

#41 Guide for Deploying the App to Digital Ocean.
  Guides/AppName.png
  Guides/AppSource.png
  Guides/BuildRun.png
  Guides/CreateApp.png
  Guides/Digital_Ocean.MD
  Guides/LaunchApp.png
Labels: Easy, SWoC2021

#48 Add the Amazon EC2 Depolyment docs
  docs/hosting.md
Labels: Easy, PR: reviewed-approved, SWoC2021

#52 Streamlit sharing done!
  Guides/StreamLit_Sharing_Guide.MD
  Guides/StreamlitDeploy.png
  Guides/StreamlitNewAppOption.png
Labels: Easy, SWoC2021

#51 added linode_guide.md
  Guides/Linode_Guide.MD
  Guides/images/1_linode.jpg
  Guides/images/2_linode.png
  Guides/images/3_linode.png
  Guides/images/4_linode.jpg
  Guides/images/5_linode.jpg
  Guides/images/6_linode.png
Labels: Easy, SWoC2021
